### ISSUE TITLE
soralog

### ISSUE THREAD

**Issue by fourseaLee** [filecoin-project/cpp-filecoin#405]
Can't compile success, Because the "filesystem" of soralog。
![图片](https://user-images.githubusercontent.com/25864430/122198093-6ac65d80-cecb-11eb-92a0-c984d84709ee.png)
I use  version  of gcc/g++ where is 7.5.
system： Ubuntu 18 server lts。

**Comment by Alexey-N-Chernyshov** [comment]
Hi, @fourseaLee! Thanks for attention to our project!
[Soralog](https://github.com/soramitsu/soralog) uses [`std::filesystem`](https://en.cppreference.com/w/cpp/filesystem) which  was partially added only to [gcc 8.0](https://en.cppreference.com/w/cpp/compiler_support) and fully supported only since gcc 9.1. Unfortunately, it is not possible to build the project with gcc prior 8.0, gcc 8.0 - 9.1 requires linking with option '-lstdc++fs', and gcc 9.1+ must be without any problem.
So, the simplest way to build the project is to update gcc to 9.1+.

**Comment by fourseaLee** [comment]
thank you， I have been upgrade。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/cpp-filecoin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月17日(星期四) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [filecoin-project/cpp-filecoin] soralog (#405)





 
Hi, @fourseaLee! Thanks for attention to our project!
 Soralog uses std::filesystem which  was partially added only to gcc 8.0 and fully supported only since gcc 9.1. Unfortunately, it is not possible to build the project with gcc prior 8.0, gcc 8.0 - 9.1 requires linking with option '-lstdc++fs', and gcc 9.1+ must be without any problem.
 So, the simplest way to build the project is to update gcc to 9.1+.
